### PR TITLE
Expand the GUI to display the color and text of titles, and fix the issue with displaying RGB colors in Lore. Update XSeries version

### PR DESCRIPTION
**Pull request by tygh89071388**

### CODE REVIEW

**Comment by chris3105x** [comment]
Hello,
thank you for your contribution to EasyPrefix.

I suggest to display the entire layout (`PREFIX + USERNAME + SUFFIX`) in the gui. This should be optional and configurable.

**Comment by tygh89071388** [comment]
> Hello, thank you for your contribution to EasyPrefix.
> 
> I suggest to display the entire layout (`PREFIX + USERNAME + SUFFIX`) in the gui. This should be optional and configurable.

Understood, if I have the time, I will make the changes and test them. The main goal of these modifications is to make the GUI more intuitive for players on my server and to fix any issues with displaying RGB colors correctly.

**Comment by chris3105x** [comment]
how are u using RGB?

**Comment by chris3105x** [comment]
interesting, because easyprefix doesn't support rgb colors ;)

**Pull request closed without merging**
